name: Weekly refresh pubs.bib

on:
  # Runs every Sunday at 04:00 UTC  (≈ midnight Saturday US-ET)
  schedule:
    - cron: '0 4 * * 0'
  workflow_dispatch:        # lets you run it manually

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Regenerate pubs.bib in-line
        run: |
          pip install scholarly==1.7.11
          python - <<'PY'
          from scholarly import scholarly
          import pathlib, datetime, sys

          USER_ID = "thCuEKEAAAAJ"    # Aykut Aksit
          out = pathlib.Path("pubs.bib")

          author = scholarly.fill(
              scholarly.search_author_id(USER_ID),
              sections=["publications"]
          )

          bibs = []
          for pub in author["publications"]:
              try:
                  bibs.append(scholarly.bibtex(pub))
              except Exception as e:
                  print("skip", e, file=sys.stderr)

          new = ("% auto-generated " + str(datetime.date.today()) + "\n\n"
                 + "\n\n".join(bibs) + "\n")

          if not out.exists() or out.read_text() != new:
              out.write_text(new)
          PY

      - name: Commit if changed
        run: |
          git config user.name  "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add pubs.bib
          git diff --cached --quiet || git commit -m "auto: update pubs.bib"
          git push
